version: "3.9"
services:
  master:
    build: .
    environment:
      - NODE_NAMES=node1 node2
    ports:
      - "8000:8000"
    container_name: master
    command: python -u ./master.py
      - master
    networks:
      - master
  sub1:
    build: sub/
    environment:
      - LATENCY=3
    ports:
      - "8080:8080"
    container_name: node1
    command: python -u ./sub.py
    depends_on:
      - master
    networks:
      - master

  sub2:
    build: sub/
    environment:
      - LATENCY=1
    ports:
      - "8090:8080"
    container_name: node2
    command: python -u ./sub.py
    depends_on:
      - master
    networks:
      - master

networks:
  master:
    driver: bridge
